AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'
Parameters:
  AppId:
    Type: String
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/timezones-update-1.0-SNAPSHOT.jar
      Handler: com.behzadian.grtzc.EnsureTimezonesUpdateHandler
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 1000
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
